{{- if .Values.database.localDeployment.deployDatabase -}}
apiVersion: v1
data:
  custom.cnf: |+
    # MariaDB database server configuration file.
    #
    # For explanations see
    # https://mariadb.com/kb/en/library/server-system-variables/
    # https://mariadb.com/kb/en/library/xtradbinnodb-server-system-variables/
    # https://mariadb.com/kb/en/library/galera-cluster-system-variables/
    # https://mariadb.com/kb/en/library/wsrep_provider_options/
    [mysqld]
    character-set-server    = utf8
    collation-server        = utf8_bin
    max_connections         = 100
    skip-ssl
    max_allowed_packet      = 128M
    query_cache_type        = OFF
    innodb_buffer_pool_dump_at_shutdown = OFF
    innodb_buffer_pool_load_at_startup  = OFF
    transaction-isolation   = REPEATABLE-READ
    innodb_flush_log_at_trx_commit = 1
    innodb_autoinc_lock_mode       = 2
    slave_exec_mode         = IDEMPOTENT
    innodb_buffer_pool_size = 384M
    innodb_log_file_size    = 64M
    binlog_format           = row
kind: ConfigMap
metadata:
  name: mariadb-configmap
{{- end -}}