{{- if .Values.ejbca.enabled -}}
{{- if .Values.ejbca.lb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ejbca.lb.name }}
  labels:
    {{- include "ejbca-ce.ejbca.labels" . | nindent 4 }}
    {{- include "ejbca-ce.lb.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "ejbca-ce.lb.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports:
  {{- range .Values.ejbca.lb.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      nodePort: {{ .nodePort }}
  {{- end }}
{{- end }}
{{- end -}}